/**
 * 视频提取技能主入口
 */

const { VideoExtractor } = require('./extractor');

/**
 * 快速提取视频内容
 * @param {string} url - 视频URL
 * @param {Object} options - 选项
 */
async function extractVideoContent(url, options = {}) {
  const extractor = new VideoExtractor();
  const result = {
    url,
    info: null,
    subtitles: null,
    transcript: null,
    summary: null
  };
  
  try {
    // 1. 获取视频信息
    console.log('[VideoSkill] 获取视频信息...');
    result.info = await extractor.getInfo(url);
    
    // 2. 尝试提取字幕
    console.log('[VideoSkill] 尝试提取字幕...');
    result.subtitles = await extractor.extractSubtitles(url, {
      languages: options.languages || ['zh-CN', 'zh-TW', 'en'],
      autoGenerated: options.autoSubtitles !== false
    });
    
    // 3. 如果没有字幕且需要转录
    if ((!result.subtitles || result.subtitles.error) && options.transcribe !== false) {
      console.log('[VideoSkill] 无字幕，开始音频转录...');
      result.transcript = await extractor.transcribe(url, {
        language: options.language || 'zh',
        model: options.model || 'base'
      });
    }
    
    // 4. 生成摘要（如果有文本）
    const textContent = result.subtitles?.rawText || result.transcript?.text;
    if (textContent && options.summarize !== false) {
      console.log('[VideoSkill] 生成内容摘要...');
      result.summary = await generateSummary(textContent);
    }
    
    return result;
    
  } catch (error) {
    console.error('[VideoSkill] 提取失败:', error.message);
    throw error;
  }
}

/**
 * 生成摘要（简化版）
 */
async function generateSummary(text) {
  // 这里可以调用LLM进行摘要
  // 简化版：提取前500字作为摘要
  const words = text.split(/\s+/);
  if (words.length <= 100) return text;
  
  return {
    preview: text.substring(0, 500) + '...',
    wordCount: words.length,
    charCount: text.length
  };
}

/**
 * 批量提取多个视频
 */
async function batchExtract(urls, options = {}) {
  const results = [];
  
  for (const url of urls) {
    try {
      const result = await extractVideoContent(url, options);
      results.push({ url, success: true, ...result });
    } catch (error) {
      results.push({ url, success: false, error: error.message });
    }
  }
  
  return results;
}

module.exports = {
  VideoExtractor,
  extractVideoContent,
  batchExtract
};
