/**
 * 视频提取技能测试
 */

const { VideoExtractor, extractVideoContent } = require('./index');

async function runTests() {
  console.log('=== 视频提取技能测试 ===\n');
  
  // 测试URL（B站）
  const testUrl = 'https://b23.tv/QzlOfdB';
  
  // 1. 基本信息获取测试
  console.log('1. 视频信息获取测试...');
  const extractor = new VideoExtractor();
  
  try {
    const info = await extractor.getInfo(testUrl);
    console.log(`  ✅ 标题: ${info.title}`);
    console.log(`  ✅ 时长: ${info.duration}秒`);
    console.log(`  ✅ 上传者: ${info.uploader}`);
    console.log(`  ✅ 有${Object.keys(info.subtitles).length}种人工字幕`);
    console.log(`  ✅ 有${Object.keys(info.automaticCaptions).length}种自动字幕`);
  } catch (error) {
    console.log(`  ❌ 失败: ${error.message}`);
  }
  
  console.log('');
  
  // 2. 字幕提取测试
  console.log('2. 字幕提取测试...');
  try {
    const subtitles = await extractor.extractSubtitles(testUrl, {
      languages: ['zh-CN'],
      autoGenerated: true
    });
    
    if (subtitles.error) {
      console.log(`  ⚠️ ${subtitles.error}`);
    } else {
      console.log(`  ✅ 字幕类型: ${subtitles.type}`);
      console.log(`  ✅ 语言: ${subtitles.language}`);
      console.log(`  ✅ 条目数: ${subtitles.content?.length || 0}`);
      console.log(`  ✅ 文本预览: ${subtitles.rawText?.substring(0, 100)}...`);
    }
  } catch (error) {
    console.log(`  ❌ 失败: ${error.message}`);
  }
  
  console.log('');
  
  // 3. 完整提取流程测试（跳过音频转录，耗时较长）
  console.log('3. 完整提取流程测试（仅字幕）...');
  try {
    const result = await extractVideoContent(testUrl, {
      transcribe: false, // 跳过音频转录
      summarize: false
    });
    
    console.log(`  ✅ 视频标题: ${result.info?.title}`);
    console.log(`  ✅ 是否提取到字幕: ${result.subtitles ? '是' : '否'}`);
    
    if (result.subtitles?.rawText) {
      console.log(`  ✅ 文本长度: ${result.subtitles.rawText.length}字符`);
    }
  } catch (error) {
    console.log(`  ❌ 失败: ${error.message}`);
  }
  
  console.log('\n=== 测试完成 ===');
}

// 运行测试
runTests().catch(console.error);
